name: Production workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
   
env:
  CI: false
jobs:
  # clear-catch:
  #   - name: clear catch
  #     run: heroku builds:cache:purge -a app
  #     with:
  #       heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #       heroku_app_name: 'restaurant-at-unimelb'
  #       heroku_email: 'yihang1@student.unimelb.edu.au'
  #       appdir: "app"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: heroku plugins:install heroku-builds
      - run: heroku builds:cache:purge -a app
      - run: npm install
        working-directory: ./app
      - run: npm run build --if-present
        working-directory: ./app
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'restaurant-at-unimelb'
          heroku_email: 'yihang1@student.unimelb.edu.au'
          appdir: "app"